### PR TITLE
Support UserAgent

### PR DESCRIPTION
**Pull request by koyachi**
# Description
Support setting and getting UserAgent.

I checked http request header contains UserAgent with [this simple http server script](https://github.com/koyachi/sketches/blob/master/2021-08-21-check-http-request-header.py).

## related issues
https://github.com/tusharojha/web_scraper/issues/8
https://github.com/tusharojha/web_scraper/issues/53

### CODE REVIEW

**Review by tusharojha — APPROVED** [review]
LGTM!

**Comment by tusharojha** [comment]
Thanks @koyachi for the contribution.

**Comment by tusharojha** [comment]
Please change the target branch to dev branch.

**Comment by koyachi** [comment]
@tusharojha I changed the target branch to develop branch.

**Pull request merged**
